# core/pr_shield.py
"""
AXELR PR Shield
===============
Generates a Markdown PR Defense Report from analysis artifacts:
    * Blast-radius dependents
    * Security findings (from CodeGuard)
    * Self-heal status (from SelfHealer)
    * Test results (optional)
    * Recommendations

Pure stdlib. RAM footprint: < 5 MB.
"""
from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any


@dataclass(slots=True)
class PRShieldInput:
    """All inputs the shield needs to render a report."""

    title: str = "Untitled Change"
    author: str | None = None
    files_changed: list[str] = field(default_factory=list)
    blast_radius: Mapping[str, Any] | None = None      # from DependencyTracker
    security_findings: list[Mapping[str, Any]] = field(default_factory=list)  # from CodeGuard
    self_heal: Mapping[str, Any] | None = None         # from SelfHealer
    test_results: Mapping[str, Any] | None = None      # {"passed": bool, "errors": [...]}
    recommendations: list[str] = field(default_factory=list)
    extra_notes: str | None = None

    def to_dict(self) -> dict:
        """Return a JSON-serialisable representation."""
        return {
            "title": self.title,
            "author": self.author,
            "files_changed": list(self.files_changed),
            "blast_radius": dict(self.blast_radius) if self.blast_radius else None,
            "security_findings": [dict(f) for f in self.security_findings],
            "self_heal": dict(self.self_heal) if self.self_heal else None,
            "test_results": dict(self.test_results) if self.test_results else None,
            "recommendations": list(self.recommendations),
            "extra_notes": self.extra_notes,
        }


class PRShield:
    """
    Stateless Markdown report builder.

    Example::

        shield = PRShield()
        md = shield.render(PRShieldInput(title="Fix login flow", ...))
    """

    __slots__ = ()

    _SEVERITY_ORDER = ("critical", "high", "medium", "low")

    # -- public API ---------------------------------------------------------

    def render(self, data: PRShieldInput) -> str:
        """Render the full Markdown report. Never raises."""
        if data is None:
            return "# PR Defense Report\n\n_No data supplied._\n"

        parts: list[str] = []
        parts.append(f"# PR Defense Report — {data.title}")
        parts.append(
            f"**Generated:** "
            f"{datetime.now(timezone.utc).isoformat(timespec='seconds')}"
        )
        if data.author:
            parts.append(f"**Author:** {data.author}")
        parts.append("")
        parts.append("---")
        parts.append("")

        try:
            parts.append(self._section_data_flow(data))
            parts.append(self._section_validation(data))
            parts.append(self._section_security(data))
            parts.append(self._section_tests(data))
            parts.append(self._section_recommendations(data))
        except Exception as exc:  # defensive — never crash the caller
            parts.append(f"\n> ⚠️ Report generation warning: {exc}\n")

        if data.extra_notes:
            parts.append("## Notes\n")
            parts.append(data.extra_notes.strip())
            parts.append("")

        parts.append("---")
        parts.append("*Report generated by AXELR PR Shield.*")
        return "\n".join(parts)

    # -- sections -----------------------------------------------------------

    def _section_data_flow(self, data: PRShieldInput) -> str:
        """Section 1 — files changed and blast radius."""
        out: list[str] = ["## 1. Data Flow & Blast Radius", ""]

        if data.files_changed:
            out.append("**Files touched:**")
            for f in data.files_changed:
                out.append(f"- `{f}`")
            out.append("")

        br = data.blast_radius
        if not br:
            out.append("_Blast-radius analysis not available._")
            out.append("")
            return "\n".join(out)

        severity = str(br.get("severity", "unknown")).upper()
        count = int(br.get("count", 0) or 0)
        out.append(f"**Severity:** `{severity}`  ")
        out.append(f"**Dependents affected:** {count}")

        dependents = list(br.get("dependents", []) or [])
        if dependents:
            out.append("")
            out.append("<details><summary>Show dependent files</summary>")
            out.append("")
            for dep in dependents[:50]:
                out.append(f"- `{dep}`")
            if len(dependents) > 50:
                out.append(f"- …and {len(dependents) - 50} more")
            out.append("")
            out.append("</details>")
        out.append("")
        return "\n".join(out)

    def _section_validation(self, data: PRShieldInput) -> str:
        """Section 2 — self-heal outcome and diff."""
        out: list[str] = ["## 2. Validation & Self-Heal", ""]

        heal = data.self_heal
        if not heal:
            out.append("_Self-heal was not attempted._")
            out.append("")
            return "\n".join(out)

        success = bool(heal.get("success", False))
        attempts = int(heal.get("attempts", 0) or 0)
        out.append(f"**Self-heal outcome:** {'✅ success' if success else '❌ failed'}")
        out.append(f"**Attempts:** {attempts}")

        err = heal.get("error")
        if err:
            out.append(f"**Error:** `{err}`")

        diff = heal.get("diff")
        if diff:
            out.append("")
            out.append("<details><summary>Show unified diff</summary>")
            out.append("")
            out.append("```diff")
            out.append(str(diff).rstrip())
            out.append("```")
            out.append("")
            out.append("</details>")

        out.append("")
        return "\n".join(out)

    def _section_security(self, data: PRShieldInput) -> str:
        """Section 3 — findings grouped by severity."""
        out: list[str] = ["## 3. Security Summary", ""]

        findings = list(data.security_findings or [])
        if not findings:
            out.append("✅ No security findings.")
            out.append("")
            return "\n".join(out)

        by_sev: dict[str, list[Mapping[str, Any]]] = {
            s: [] for s in self._SEVERITY_ORDER
        }
        for f in findings:
            sev = str(f.get("severity", "low")).lower()
            by_sev.setdefault(sev, []).append(f)

        for sev in self._SEVERITY_ORDER:
            bucket = by_sev.get(sev) or []
            if not bucket:
                continue
            out.append(f"### {sev.title()} ({len(bucket)})")
            out.append("")
            out.append("| Type | Line | Message |")
            out.append("|------|------|---------|")
            for f in bucket:
                ftype = self._escape_cell(str(f.get("type", "")))
                line = f.get("line", 0)
                msg = self._escape_cell(str(f.get("message", "")))
                out.append(f"| {ftype} | {line} | {msg} |")
            out.append("")

        out.append(f"**Total findings:** {len(findings)}")
        out.append("")
        return "\n".join(out)

    def _section_tests(self, data: PRShieldInput) -> str:
        """Section 4 — test results."""
        out: list[str] = ["## 4. Test Results", ""]

        tr = data.test_results
        if not tr:
            out.append("_No test results were supplied._")
            out.append("")
            return "\n".join(out)

        passed = bool(tr.get("passed", False))
        out.append(f"**Status:** {'✅ passed' if passed else '❌ failed'}")

        errors = list(tr.get("errors", []) or [])
        if errors:
            out.append("")
            out.append(f"**Failures ({len(errors)}):**")
            for e in errors[:20]:
                if isinstance(e, Mapping):
                    msg = str(e.get("message", e))
                else:
                    msg = str(e)
                out.append(f"- {msg}")
            if len(errors) > 20:
                out.append(f"- …and {len(errors) - 20} more")
        out.append("")
        return "\n".join(out)

    def _section_recommendations(self, data: PRShieldInput) -> str:
        """Section 5 — recommendations (auto-generated if none supplied)."""
        out: list[str] = ["## 5. Recommendations", ""]

        recs: list[str] = list(data.recommendations or [])
        if not recs:
            recs.extend(self._auto_recommendations(data))

        if not recs:
            out.append("_No recommendations._")
        else:
            for r in recs:
                out.append(f"- {r}")
        out.append("")
        return "\n".join(out)

    # -- helpers ------------------------------------------------------------

    @staticmethod
    def _auto_recommendations(data: PRShieldInput) -> list[str]:
        """Derive actionable recommendations from the inputs."""
        recs: list[str] = []

        br = data.blast_radius or {}
        if str(br.get("severity", "")).lower() == "high":
            recs.append(
                "Blast radius is **high** — request reviews from owners of the "
                "listed dependent modules before merging."
            )

        critical = [
            f for f in (data.security_findings or [])
            if str(f.get("severity", "")).lower() == "critical"
        ]
        if critical:
            recs.append(
                f"{len(critical)} critical security finding(s) must be resolved "
                "before merge."
            )

        heal = data.self_heal or {}
        if heal and not heal.get("success", False):
            recs.append("Self-heal failed — inspect the diff manually.")

        tests = data.test_results or {}
        if tests and not tests.get("passed", False):
            recs.append("Fix failing tests before merging.")

        if not recs:
            recs.append("No blocking issues detected. Proceed with normal review.")
        return recs

    @staticmethod
    def _escape_cell(text: str) -> str:
        """Escape pipe and newline characters for Markdown table cells."""
        return text.replace("|", "\\|").replace("\n", " ")


__all__ = ["PRShield", "PRShieldInput"]